INSERT INTO District (code, name) VALUES (1,Aveiro),
(2,Beja),
(3,Braga),
(4,Bragan�a),
(5,Castelo Branco),
(6,Coimbra),
(7,�vora),
(8,Faro),
(9,Guarda),
(10,Leiria),
(11,Lisboa),
(12,Portalegre),
(13,Porto),
(14,Santar�m),
(15,Set�bal),
(16,Viana do Castelo),
(17,Vila Real),
(18,Viseu),
(31,Ilha da Madeira),
(32,Ilha de Porto Santo),
(41,Ilha de Santa Maria),
(42,Ilha de S�o Miguel),
(43,Ilha Terceira),
(44,Ilha Graciosa),
(45,Ilha de S�o Jorge),
(46,Ilha do Pico),
(47,Ilha do Faial),
(48,Ilha das Flores),
(49,Ilha do Corvo;
INSERT INTO Municipality (code, name, email, district) VALUES(1,corvo,cmcorvo@mail.telepac.pt,49),
(2,santa cruz das flores,geral@,48),
(3,s�o roque do pico,null,46),
(4,povoa��o,null,42),
(5,ribeira grande,geralcmrg@cm-ribeiragrande.pt,42),
(6,vila franca do campo,geral@cmvfc.pt,42),
(7,ribeira brava,geral@cm-ribeirabrava.pt,31),
(8,santa cruz,geral@cm-santacruz.pt,31),
(9,santana,secretaria@cm-santana.com,31),
(10,s�o vicente,null,31),
(11,penalva do castelo,geral@cm-penalvadocastelo.pt,18),
(12,penedono,cm-penedono@cm-penedono.pt,18),
(13,resende,geral@cm-resende.pt,18),
(14,santa comba d�o,null,18),
(15,s�o jo�o da pesqueira,null,18),
(16,s�o pedro do sul,null,18),
(17,s�t�o,null,18),
(18,sernancelhe,geral@cm-sernancelhe.pt,18),
(19,tabua�o,null,18),
(20,tarouca,camara@cm-tarouca.pt,18),
(21,tondela,geral@cm-tondela.pt,18),
(22,vila nova de paiva,geral@cm-vnpaiva.pt,18),
(23,viseu,apoiomunicipe@cmviseu.pt,18),
(24,vouzela,geral@cm-vouzela.pt,18;
INSERT INTO Town (code, name, municipality) VALUES (88,Uni�o das freguesias de Selho S�o Louren�o e Gominh�es,8),
(01,Corvo,1),
(89,Uni�o das freguesias de Serzedo e Calvos,8),
(02,Cedros,2),
(03,Ponta Delgada,2),
(04,Santa Cruz das Flores,2),
(05,Lajes das Flores,1),
(06,Lomba,1),
(07,Mosteiro,1),
(08,Horta (Matriz),1),
(09,Pedro Miguel,1),
(90,Uni�o das freguesias de Souto Santa Maria,8),
(91,Uni�o das freguesias de Tabuadelo e S�o Faustino,8),
(92,Uni�o das freguesias de Areias de Vilar e Encourados,2),
(93,Uni�o das freguesias de Barcelos,2),
(94,Uni�o das freguesias de Campo e Tamel (S�o Pedro Fins),2),
(95,Uni�o das freguesias de Carreira e Fonte Coberta,2),
(96,Uni�o das freguesias de Chorente,2),
(97,Uni�o das freguesias de Creixomil e Mariz,2),
(10,Praia do Almoxarife,1),
(98,Uni�o das freguesias de Durr�es e Tregosa,2),
(11,Praia do Norte,1),
(99,Uni�o das freguesias de Gamil e Mid�es,2),
(12,Ribeirinha,1),
(13,Sal�o,1),
(14,S�o Bartolomeu de Regatos,1),
(15,S�o Bento,1),
(16,S�o Mateus da Calheta,1),
(17,Serreta,1),
(18,Terra Ch�,1),
(19,Vila de S�o Sebasti�o,1),
(20,Santo Ant�nio,3),
(21,S�o Vicente Ferreira,3),
(22,Sete Cidades,3),
(23,Ajuda da Bretanha,3),
(24,Pilar da Bretanha,3),
(25,Santa Clara,3),
(26,Uni�o das freguesias de Bigorne,5),
(27,S�o Jo�o de Lourosa,23),
(28,Uni�o das freguesias de Caparrosa e Silvares,21),
(29,S�o Pedro de France,23),
(30,Uni�o das freguesias de S�o Jo�o do Monte e Mosteirinho,21),
(31,Uni�o das freguesias de S�o Miguel do Outeiro e Sabugosa,21),
(32,Uni�o das freguesias de Tondela e Nandufe,21),
(33,Uni�o das freguesias de Vilar de Besteiros e Mosteiro de Fr�guas,21),
(34,Uni�o das freguesias de Mou��s e Lamares,14),
(35,Uni�o das freguesias de Barreiros e Cep�es,23),
(36,Uni�o das freguesias de Boa Aldeia,23),
(37,Uni�o das freguesias de Couto de Baixo e Couto de Cima,23),
(38,Uni�o das freguesias de Fa�l e Vila Ch� de S�,23),
(39,Uni�o das freguesias de Repeses e S�o Salvador,23),
(40,Uni�o das freguesias de S�o Cipriano e Vil de Souto,23),
(41,Viseu,23),
(42,Uni�o das freguesias de Viade de Baixo e Fervidelas,6),
(43,Uni�o das freguesias de Vilar de Perdizes e Meixide,6),
(44,Vilar de Nantes,3),
(45,Vilarelho da Raia,3),
(46,Uni�o das freguesias de Subportela,9),
(47,Vilas Boas,3),
(48,Vilela Seca,3),
(49,Vilela do T�mega,3),
(50,Santa Maria Maior,3),
(51,Vila Fernando,7),
(52,Arca e Ponte de Lima,7),
(53,Planalto de Monforte (Uni�o das freguesias de Oucidres e Bobadela),3),
(54,Uni�o das freguesias da Madalena e Samai�es,3),
(55,Uni�o das freguesias das Eiras,3),
(56,Uni�o das freguesias de Calv�o e Soutelinho da Raia,3),
(57,Uni�o das freguesias de Loivos e P�voa de Agra��es,3),
(58,Uni�o das freguesias de Santa Cruz/Trindade e Sanjurge,3),
(59,Uni�o das freguesias de Soutelo e Seara Velha,3),
(60,Uni�o das freguesias de Travancas e Roriz,3),
(61,Vidago (Uni�o das freguesias de Vidago,3),
(FA,Uni�o das freguesias de Milhazes,2),
(FB,Uni�o das freguesias de Negreiros e Chav�o,2),
(62,Uni�o das freguesias de Souto e Taba��,1),
(63,Uni�o das freguesias de T�vora (Santa Maria e S�o Vicente),1),
(FC,Uni�o das freguesias de Quinti�es e Aguiar,2),
(64,Uni�o das freguesias de Vilela,1),
(FD,Uni�o das freguesias de Sequeade e Bastu�o (S�o Jo�o e Santo Estev�o),2),
(65,Santa Maria Maior,6),
(FE,Uni�o das freguesias de Silveiros e Rio Covo (Santa Eul�lia),2),
(FF,Uni�o das freguesias de Tamel (Santa Leoc�dia) e Vilar do Monte,2),
(66,Santo Ant�nio,6),
(FG,Uni�o das freguesias de Viatodos,2),
(67,S�o Vicente,6),
(68,Uni�o das freguesias de Valbom (S�o Pedro),13),
(FH,Uni�o das freguesias de Vila Cova e Feitos,2),
(69,Uni�o das freguesias do Vade,13),
(70,Vila Verde e Barbudo,13),
(71,Urgezes,8),
(72,Uni�o das freguesias de Guisande e Oliveira (S�o Pedro),3),
(73,Uni�o das freguesias de Lomar e Arcos,3),
(74,Uni�o das freguesias de Merelim (S�o Paio),3),
(75,Uni�o das freguesias de Aba��o e G�meos,8),
(76,Uni�o das freguesias de Air�o Santa Maria,8),
(77,Uni�o das freguesias de Arosa e Castel�es,8),
(78,Uni�o das freguesias de At�es e Rendufe,8),
(79,Uni�o das freguesias de Briteiros Santo Est�v�o e Donim,8),
(80,Uni�o das freguesias de Briteiros S�o Salvador e Briteiros Santa Leoc�dia,8),
(81,Uni�o das freguesias de Candoso S�o Tiago e Mascotelos,8),
(82,Uni�o das freguesias de Conde e Gandarela,8),
(83,Uni�o das freguesias de Leit�es,8),
(84,Uni�o das freguesias de Oliveira,8),
(85,Uni�o das freguesias de Prazins Santo Tirso e Corvite,8),
(86,Uni�o das freguesias de Sande S�o Louren�o e Balazar,8),
(87,Uni�o das freguesias de Sande Vila Nova e Sande S�o Clemente,8;
